pipeline {
  agent {
    docker {
      image 'centos'
      label 'my-helloworld'
      args '-v /tmp:/tmp'
    }
  }
  stages {
    stage('Stage 1') {
      steps {
        echo 'Hello World!'
      }
    }
  }
}
